import bot

while True:
    bot.exception('test')
    
